name: Reusable test workflow

on:
  workflow_call:

jobs:
  gradleValidation:
    name: Gradle Wrapper
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Gradle Wrapper Validation
        uses: gradle/wrapper-validation-action@v1.0.6

  codeInspection:
    name: Code Inspection
    needs: gradleValidation
    runs-on: ubuntu-latest
    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Qodana - Code Inspection
        uses: JetBrains/qodana-action@v5.0.2

  test:
    name: Test
    needs: gradleValidation
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        gradleVersion:
          - 6.6.1
          - 6.9.2
          - 7.4.2
        os:
          - windows-latest
          - ubuntu-latest
          - macos-latest

    steps:

      - name: Fetch Sources
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
          cache: gradle

      - name: Run Linters and Test
        run: ./gradlew check -PtestGradleVersion="${{ matrix.gradleVersion }}"

      - name: Collect Test Results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: test-results-${{ matrix.gradleVersion }}-${{ runner.os }}
          path: ${{ github.workspace }}/build/reports/tests
